index:
  template: "{env}-{id}-{application_name}{stack_name}-user-transactables-{version}"
doc_types:
  user:
    source: User
    scope: indexable
    mapping:
      options: {}

  location:
    source: Location
    scope: indexable
    mapping:
      options:
        _parent: { type: 'user' }

    parent_id: creator_id

  transactable:
    source: Transactable
    scope: indexable
    mapping:
      options:
        _parent: { type: 'location' }
    parent_id: location_id
