Documentation:
  Enabled: false
AllCops:
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: false
Style/IfUnlessModifier:
  MaxLineLength: 130
Style/WhileUntilModifier:
  MaxLineLength: 130
Metrics/LineLength:
  Max: 130
Layout/TrailingWhitespace:
  Enabled: false
