name: Service
slug: 'service'
show_path_format: '/:transactable_type_id/:id'
searchable: false
skip_payment_authorization: false
hours_for_guest_to_confirm_payment: 24
single_transactable: true
skip_location: true
bookable_noun: 'Service'
enable_photo_required: false
lessor: 'Carer'
lessee: 'Individual'
enable_reviews: true
auto_accept_invitation_as_collaborator: true
require_transactable_during_onboarding: false
access_restricted_to_invited: false

action_types:
  - enabled: true
    service_fee_guest_percent: 0
    service_fee_host_percent: 0
    minimum_booking_minutes: 60
    hours_to_expiration: 24
    cancellation_policy_enabled: '1'
    cancellation_policy_hours_for_cancellation: 24
    cancellation_policy_penalty_percentage: 0
    cancellation_policy_penalty_hours: 1
    confirm_reservations: true
    send_alert_hours_before_expiry: false
    send_alert_hours_before_expiry_hours: 0
    minimum_lister_service_fee_cents: 0
    both_side_confirmation: false
    allow_drafts: false
    type: TransactableType::TimeBasedBooking
    pricings:
      - number_of_units: 1
        unit: 'hour'
        min_price_cents:
        max_price_cents:
        allow_free_booking: false
        order_class_name: 'Reservation'
        allow_nil_price_cents: false

custom_attributes:
  - name: ndis_category
    label: 'NDIS Category'
    html_tag: 'input'
    attribute_type: string
    validation:
      required: false

validation:
  - field_name: name
    required: false

form_components:
