common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: saiperchard
  password:
  min_messages: warning
  host: localhost

development:
  <<: *common
  database: desksnearme_development

test: &test
  <<: *common
  database: desksnearme_tests

cucumber:
  <<: *test
