common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= `whoami`.chomp %>
  password:
  min_messages: warning

development:
  <<: *common
  database: desksnearme_development

test: &test
  <<: *common
  database: desksnearme_tests

cucumber:
  <<: *test
