common: &default_settings
  license_key: 'd37590e50f88575698b56c3aab713e5bd491afb8'
  app_name: Desks Near Me
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  audit_log:
    enabled: false
  capture_params: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: "ActionController::RoutingError,Listing::NotFound,Location::NotFound,Page::NotFound"

development:
  developer_mode: true
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  license_key: '3b6a804ef6f75377d8663c01528800e6525a0e0f'
  app_name: Desks Near Me (Staging)
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  audit_log:
    enabled: false
  capture_params: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: "ActionController::RoutingError,Listing::NotFound,Location::NotFound,Page::NotFound"
