test: &default
  username: krajek6-facilitator_api1.gmail.com
  password: 1387036911
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AxwnuWpf4utTFjXHLNnwOYQV9O7.
  app_id: APP-80W284485P519543T
  http_timeout: 30
  sandbox_email_address: krajek6-facilitator@gmail.com

  client_id: AYtqmBDI2fiAdHBKci0Z9Heg05ackesUQ7_FcUUI1vfzwn8AOMltMhlwscFq
  client_secret: EDCqQxAOj9SSxHvZiBkPunlHXk-qQLLPppQYjL3F7ltmSY1e4jp6xWtgwjJy
  mode: sandbox

development:
  <<: *default

staging:
  <<: *default

production:
  client_id: AbT56hCquUciJvXz3SK7loxk9TIVtoYcxJ53w-ac5E7BlJfFdkN3tlPjiz-W
  client_secret: EB3XtBDC9SW1TD84r8wvxv3jBNiND7k9X_Tz6G7IrCYc17jeIUlr66XUCPgU
  mode: live
