test: &default

  # Credentials for REST APIs
  client_id: AYtqmBDI2fiAdHBKci0Z9Heg05ackesUQ7_FcUUI1vfzwn8AOMltMhlwscFq
  client_secret: EDCqQxAOj9SSxHvZiBkPunlHXk-qQLLPppQYjL3F7ltmSY1e4jp6xWtgwjJy

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: DesksNearMe DevelopmentAPP-31C982222W793760V
  username: krajek6-facilitator_api1.gmail.com
  password: 1387036911
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AxwnuWpf4utTFjXHLNnwOYQV9O7.
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: krajek6-facilitator@gmail.com

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  mode: live
