-
  name: 'shippo'
  countries:
    - USA
    - UK
    - Germany
    - France
    - Canada
  fields:
    - api_key
    - environment

-
  name: 'manual'
  quote:
    gross: 0
  countries:
    - Australia
  fields:
    - environment

-
  name: 'auspost-manual'
  url: 'https://auspost.com.au/'
  quote:
    gross: 1000
  countries:
    - Australia
  fields:
    - environment

-
  name: 'sendle'
  countries:
    - Australia
  fields:
    - api_key
    - sendle_id
    - environment
