# default profile
name: Default
profile_type: default

custom_attributes:
  - name: role
    public: false
    html_tag: select
    label: Role
    searchable: true
    validation:
      valid_values: [ 'Superfan', 'Fan', 'Artist', 'Community Friend', 'Charter Member' ]
      required: false

  - name: about_me
    html_tag: textarea
    attribute_type: string
    input_html_options: { cols: 40, rows: 8 }
    label: About me
    search_in_query: true
    validation:
      max_length: 5000

  - name: short_bio
    html_tag: textarea
    attribute_type: text
    input_html_options: { cols: 40, rows: 8 }
    label: Short bio
    search_in_query: true
    validation:
      max_length: 140

  - name: date_of_birth
    html_tag: input
    attribute_type: date
    label: Date of Birth
    search_in_query: false

  - name: member_since
    html_tag: input
    attribute_type: datetime
    label: Member Since
    search_in_query: false

  - name: member_year
    html_tag: input
    attribute_type: datetime
    label: Member Year
    search_in_query: false
