name: Product / Service listing item
instance_profile_types: [Buyer]

custom_attributes:
  - name: title
    label: Title
    attribute_type: string
    html_tag: input
  - name: description
    label: Description
    attribute_type: string
    html_tag: textarea

